"""Application use cases and ports."""

from closeros.application.authentication_issuance import (
    AuthenticationSessionRotation,
    AuthenticationSessionTransitionError,
    IssuedAuthenticationOneTimeToken,
    IssuedAuthenticationSession,
    complete_pending_mfa_and_rotate_session,
    issue_authenticated_session,
    issue_authentication_one_time_token,
    issue_pending_mfa_session,
)
from closeros.application.authentication_notification_delivery import (
    AuthenticationNotificationDelivery,
)
from closeros.application.authentication_persistence import (
    AuthenticationPersistenceError,
    AuthenticationRecordNotFoundError,
    AuthenticationReferenceError,
    AuthenticationUnitOfWork,
    CredentialRepository,
    DuplicateCredentialEmailError,
    DuplicateOneTimeTokenError,
    DuplicateSessionTokenError,
    DuplicateUserCredentialError,
    OneTimeTokenRepository,
    SessionRepository,
    UserRepository,
)
from closeros.application.authentication_workflows import (
    AUTHENTICATION_FAILED_MESSAGE,
    AUTHENTICATION_REQUEST_ACCEPTED_MESSAGE,
    AUTHENTICATION_UNAVAILABLE_MESSAGE,
    REGISTRATION_UNAVAILABLE_MESSAGE,
    AuthenticationFailedError,
    AuthenticationRequestAccepted,
    AuthenticationWorkflowService,
    AuthenticationWorkflowUnavailableError,
    MfaRequirementPolicy,
    MfaVerifier,
    RegistrationResult,
    RegistrationUnavailableError,
    ResolvedAuthenticationSession,
)
from closeros.application.password_hashing import (
    PasswordHasher,
    PasswordVerification,
)

__all__ = [
    "AUTHENTICATION_FAILED_MESSAGE",
    "AUTHENTICATION_REQUEST_ACCEPTED_MESSAGE",
    "AUTHENTICATION_UNAVAILABLE_MESSAGE",
    "REGISTRATION_UNAVAILABLE_MESSAGE",
    "AuthenticationFailedError",
    "AuthenticationNotificationDelivery",
    "AuthenticationPersistenceError",
    "AuthenticationRecordNotFoundError",
    "AuthenticationReferenceError",
    "AuthenticationRequestAccepted",
    "AuthenticationSessionRotation",
    "AuthenticationSessionTransitionError",
    "AuthenticationUnitOfWork",
    "AuthenticationWorkflowService",
    "AuthenticationWorkflowUnavailableError",
    "CredentialRepository",
    "DuplicateCredentialEmailError",
    "DuplicateOneTimeTokenError",
    "DuplicateSessionTokenError",
    "DuplicateUserCredentialError",
    "IssuedAuthenticationOneTimeToken",
    "IssuedAuthenticationSession",
    "MfaRequirementPolicy",
    "MfaVerifier",
    "OneTimeTokenRepository",
    "PasswordHasher",
    "PasswordVerification",
    "RegistrationResult",
    "RegistrationUnavailableError",
    "ResolvedAuthenticationSession",
    "SessionRepository",
    "UserRepository",
    "complete_pending_mfa_and_rotate_session",
    "issue_authenticated_session",
    "issue_authentication_one_time_token",
    "issue_pending_mfa_session",
]
